In [1]:
import math
import numpy as np
import pandas  as pd 
import matplotlib as plot

In [2]:
def lcm (a,b):
    return int((a*b)/math.gcd(a,b))

def del_spec(a,b,N,k,n):
    ds = np.zeros(n)
    for i in range(0,n):
        ds[i] = N-b*(math.floor(i/a))-(i%a)
    return ds

# SDE

## Program for finding test cases satisfying the constraints

In [5]:
cnt1 = 0
cnt2= 0
CNT = 0

for T in range(4,40):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                        if(a1==a2  and T >= b2 + b1):
                            flag_dc = 0
                            flag_check = 0
                            max_del = -1
                            max_del_ind = -1
                            k = max(a1,a2)*min((T-b2-a1+1)/b1,(T-b1-a2+1)/b2)
                            if(k.is_integer()):
                                k = int(k)
                                CNT+=1
                                N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
                                N2 = (k+a2-1)+(b2-a2)*math.floor((k+a2-1)/a2)+1
                                if (N1<=T-b2+1 and N2<=T-b1+1):
                                    cnt1+= 1
                                    ds1=del_spec(a1,b1,N1-1,k,k+a1)
                                    ds2=del_spec(a2,b2,N2-1,k,k+a2)
                                    for i in range(0,k):
                                        if (ds1[i]+ ds2[k-i-1])>T:
                                            flag_dc = 1

                                    if(flag_dc == 1):
                                        cnt2 +=1
                                        print(k,a1,a2,T,b1,b2,N1,N2)
                                        print(ds1)
                                        print(ds2)

In [6]:
CNT

6345

In [7]:
cnt1

4278

In [8]:
cnt2

0

## Program for finding max rate using SDE

In [9]:
pd.set_option("display.max_rows", 10)

In [10]:
data = []
data_m = []

cnt = 0 
CNT = 0
CNT2 = 0

for T in range(4,20):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                    if(T >= b1 + b2):
                        R1_opt= (T-b2-a1+1)/(T-b2-a1+1+b1)
                        R2_opt= (T-b1-a2+1)/(T-b1-a2+1+b2)
                        R_opt = min(R1_opt,R2_opt)
                        R_max = -1
                        k_max = -1
                        cnt+=1 
                        for k in range(1,min((T-b2+1-a1),(T-b1+1-a2))+1):
                            R=-1 
                            R1 = -1 
                            R2 = -1 
                            flag_dc = 0
                            N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
                            N2 = (k+a2-1)+(b2-a2)*math.floor((k+a2-1)/a2)+1
                            if(N1<=T-b2+1) and (N2<=T-b1+1):
                                CNT+=1
                                ds1=del_spec(a1,b1,N1-1,k,k+a1)
                                ds2=del_spec(a2,b2,N2-1,k,k+a2)
                                for i in range(0,k):
                                    if (ds1[i]+ ds2[k-i-1])>T:
                                        flag_dc = 1
                                if(flag_dc == 0):
                                    CNT2+=1
                                    R1 = k/(k+a1)
                                    R2 = k/(k+a2)
                                    R = min(R1,R2)
                                    if(R>R_max):
                                        k_max = k 
                                        R_max = R
                                data.append((T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt))                               
                        data_m.append((T,a1,b1,a2,b2,k_max,R_max,R_opt,R_max==R_opt))

In [11]:
cnt

15504

In [12]:
CNT

30725

In [13]:
CNT2

30357

In [14]:
df = pd.DataFrame(data, columns = ['T', 'a1',"b1","N1","a2","b2","N2","k","R1","R1_opt","R2","R2_opt","R","R_opt"])
df_m = pd.DataFrame(data_m, columns = ['T', 'a1',"b1","a2","b2","k_max","R_max","R_opt","Optimal?"])

In [15]:
df

,T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt
0,4,1,2,3,1,2,3,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
1,5,1,2,3,1,2,3,1,0.500000,0.600000,0.500000,0.6,0.500000,0.600000
2,5,1,2,3,1,3,4,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
3,5,1,3,4,1,2,3,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
4,5,1,2,3,2,3,4,1,0.500000,0.500000,0.333333,0.4,0.333333,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30720,19,15,16,17,1,2,3,1,0.062500,0.157895,0.500000,0.6,0.062500,0.157895
30721,19,15,16,17,1,3,4,1,0.062500,0.111111,0.500000,0.5,0.062500,0.111111
30722,19,15,17,18,1,2,3,1,0.062500,0.150000,0.500000,0.5,0.062500,0.150000
30723,19,15,16,17,2,3,4,1,0.062500,0.111111,0.333333,0.4,0.062500,0.111111
30724,19,16,17,18,1,2,3,1,0.058824,0.105263,0.500000,0.5,0.058824,0.105263

In [16]:
yf = df[df["R"]!=-1]
# yf[yf["k"]>yf["a1"]]
# yf[yf["R"]==yf["R_opt"]]
yf

,T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt
0,4,1,2,3,1,2,3,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
1,5,1,2,3,1,2,3,1,0.500000,0.600000,0.500000,0.6,0.500000,0.600000
2,5,1,2,3,1,3,4,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
3,5,1,3,4,1,2,3,1,0.500000,0.500000,0.500000,0.5,0.500000,0.500000
4,5,1,2,3,2,3,4,1,0.500000,0.500000,0.333333,0.4,0.333333,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30720,19,15,16,17,1,2,3,1,0.062500,0.157895,0.500000,0.6,0.062500,0.157895
30721,19,15,16,17,1,3,4,1,0.062500,0.111111,0.500000,0.5,0.062500,0.111111
30722,19,15,17,18,1,2,3,1,0.062500,0.150000,0.500000,0.5,0.062500,0.150000
30723,19,15,16,17,2,3,4,1,0.062500,0.111111,0.333333,0.4,0.062500,0.111111
30724,19,16,17,18,1,2,3,1,0.058824,0.105263,0.500000,0.5,0.058824,0.105263

In [17]:
yf = df[df["R"]==-1]
# yf[yf["k"]>yf["a1"]]
# yf[yf["R"]==yf["R_opt"]]
yf

,T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt
237,9,2,3,7,2,3,7,3,-1.0,0.625000,-1.0,0.625000,-1.0,0.625000
350,10,1,2,7,2,4,9,3,-1.0,0.750000,-1.0,0.636364,-1.0,0.636364
428,10,2,4,9,1,2,7,3,-1.0,0.636364,-1.0,0.750000,-1.0,0.636364
805,11,2,3,7,2,4,9,3,-1.0,0.666667,-1.0,0.636364,-1.0,0.636364
815,11,2,4,9,2,3,7,3,-1.0,0.636364,-1.0,0.666667,-1.0,0.636364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28201,19,5,7,15,4,5,12,6,-1.0,0.588235,-1.0,0.642857,-1.0,0.588235
28307,19,5,6,14,5,6,14,7,-1.0,0.600000,-1.0,0.600000,-1.0,0.600000
28738,19,6,7,15,2,3,13,7,-1.0,0.611111,-1.0,0.785714,-1.0,0.611111
28875,19,6,7,15,3,4,13,7,-1.0,0.588235,-1.0,0.714286,-1.0,0.588235
29004,19,6,7,15,4,5,13,7,-1.0,0.562500,-1.0,0.642857,-1.0,0.562500

In [18]:
df_m

        T  a1  b1  a2  b2  k_max     R_max     R_opt  Optimal?
0       4   1   2   1   2      1  0.500000  0.500000      True
1       5   1   2   1   2      1  0.500000  0.600000     False
2       5   1   2   1   3      1  0.500000  0.500000      True
3       5   1   3   1   2      1  0.500000  0.500000      True
4       5   1   2   2   3      1  0.333333  0.400000     False
...    ..  ..  ..  ..  ..    ...       ...       ...       ...
15499  19  15  16   1   2      1  0.062500  0.157895     False
15500  19  15  16   1   3      1  0.062500  0.111111     False
15501  19  15  17   1   2      1  0.062500  0.150000     False
15502  19  15  16   2   3      1  0.062500  0.111111     False
15503  19  16  17   1   2      1  0.058824  0.105263     False

[15504 rows x 9 columns]

In [19]:
yf_m = df_m[df_m["R_max"]==-1]
yf_m

Empty DataFrame
Columns: [T, a1, b1, a2, b2, k_max, R_max, R_opt, Optimal?]
Index: []

## Maximum Rate using SDE for a given set of (T,a1,b1,a2,b2)

In [20]:
T = 8
a1 = 3
b1 = 4 
a2 = 3
b2 = 4

cnt = 0 
CNT = 0
CNT2 = 0

if(T>= b1 + b2):
    R1_opt= (T-b2-a1+1)/(T-b2-a1+1+b1)
    R2_opt= (T-b1-a2+1)/(T-b1-a2+1+b2)
    R_opt = min(R1_opt,R2_opt)
    R_max = -1
    k_max = -1
    cnt+=1 
    for k in range(1,min((T-b2+1-a1),(T-b1+1-a2))+1):
        R=-1 
        R1 = -1 
        R2 = -1 
        flag_dc = 0
        N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
        N2 = (k+a2-1)+(b2-a2)*math.floor((k+a2-1)/a2)+1
        if(N1<=T-b2+1) and (N2<=T-b1+1):
            CNT+=1
            ds1=del_spec(a1,b1,N1-1,k,k+a1)
            ds2=del_spec(a2,b2,N2-1,k,k+a2)
            
            for i in range(0,k):
                if (ds1[i]+ ds2[k-i-1])>T:
                    flag_dc = 1
            if(flag_dc == 0):
                CNT2+=1
                R1 = k/(k+a1)
                R2 = k/(k+a2)
                R = min(R1,R2)
                if(R>R_max):
                    k_max = k 
                    R_max = R
            print(T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt)
            print(ds1,ds2)

8 3 4 5 3 4 5 1 0.25 0.3333333333333333 0.25 0.3333333333333333 0.25 0.3333333333333333
[4. 3. 2. 0.] [4. 3. 2. 0.]

In [21]:
5/17

0.29411764705882354

## Characterizing Maximum Rate using SDE

In [22]:
pd.set_option("display.max_rows", 10)

In [21]:
cnt = 0 
CNT = 0
CNT2 = 0
data = []
data_m = []
for T in range(4,30):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                    if(T >= b1 + b2):
                        R1_opt= (T-b2-a1+1)/(T-b2-a1+1+b1)
                        R2_opt= (T-b1-a2+1)/(T-b1-a2+1+b2)
                        R_opt = min(R1_opt,R2_opt)
                        R_max = -1
                        k_max = -1
                        cnt+=1 
                        m1 = math.floor((T-b2+1)/b1)
                        d1 = (T-b2+1)%b1 
                        d1_dash = min(a1,d1)
                        k1 = (m1-1)*a1 + d1_dash
                        m2 = math.floor((T-b1+1)/b2)
                        d2 = (T-b1+1)%b2 
                        d2_dash = min(a2,d2)
                        k2 = (m2-1)*a2 + d2_dash   
                        for k in range(1,min((T-b2+1-a1),(T-b1+1-a2))+1):
                            R=-1 
                            R1 = -1 
                            R2 = -1 
                            flag_dc = 0
                            N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
                            N2 = (k+a2-1)+(b2-a2)*math.floor((k+a2-1)/a2)+1
                            if(N1<=T-b2+1) and (N2<=T-b1+1):
                                CNT+=1
                                ds1=del_spec(a1,b1,N1-1,k,k+a1)
                                ds2=del_spec(a2,b2,N2-1,k,k+a2)
                                for i in range(0,k):
                                    if (ds1[i]+ ds2[k-i-1])>T:
                                        flag_dc = 1
                                if(flag_dc == 0):
                                    CNT2+=1
                                    R1 = k/(k+a1)
                                    R2 = k/(k+a2)
                                    R = min(R1,R2)
                                    if(R>R_max):
                                        k_max = k 
                                        R_max = R
                                data.append((T,a1,b1,N1,a2,b2,N2,k,R1,R1_opt,R2,R2_opt,R,R_opt))                               
                        data_m.append((T,a1,b1,a2,b2,k_max,k1,m1,d1,k2,m2,d2,R_max,R_opt))

In [22]:
df = pd.DataFrame(data, columns = ['T', 'a1',"b1","N1","a2","b2","N2","k","R1","R1_opt","R2","R2_opt","R","R_opt"])
df_m = pd.DataFrame(data_m, columns = ['T', 'a1',"b1","a2","b2","k_max","k1","m1","d1","k2","m2","d2","R_max","R_opt"])

In [23]:
df_m

         T  a1  b1  a2  b2  k_max  k1  m1  d1  k2  m2  d2     R_max     R_opt
0        4   1   2   1   2      1   1   1   1   1   1   1  0.500000  0.500000
1        5   1   2   1   2      1   1   2   0   1   2   0  0.500000  0.600000
2        5   1   2   1   3      1   1   1   1   1   1   1  0.500000  0.500000
3        5   1   3   1   2      1   1   1   1   1   1   1  0.500000  0.500000
4        5   1   2   2   3      1   1   1   1   1   1   1  0.333333  0.400000
...     ..  ..  ..  ..  ..    ...  ..  ..  ..  ..  ..  ..       ...       ...
142501  29  25  26   1   2      1   2   1   2   1   2   0  0.038462  0.103448
142502  29  25  26   1   3      1   1   1   1   1   1   1  0.038462  0.071429
142503  29  25  27   1   2      1   1   1   1   1   1   1  0.038462  0.100000
142504  29  25  26   2   3      1   1   1   1   1   1   1  0.038462  0.071429
142505  29  26  27   1   2      1   1   1   1   1   1   1  0.037037  0.068966

[142506 rows x 14 columns]

In [24]:
cnt

142506

In [25]:
df_m["delta_min"] = df_m[["k1","k2"]].min(axis=1) - df_m["k_max"]
df_m["T1"] = df_m["T"]-df_m["b2"]
df_m["T2"] = df_m["T"]-df_m["b1"]
df_m

,T,a1,b1,a2,b2,k_max,k1,m1,d1,k2,m2,d2,R_max,R_opt,delta_min,T1,T2
0,4,1,2,1,2,1,1,1,1,1,1,1,0.500000,0.500000,0,2,2
1,5,1,2,1,2,1,1,2,0,1,2,0,0.500000,0.600000,0,3,3
2,5,1,2,1,3,1,1,1,1,1,1,1,0.500000,0.500000,0,2,3
3,5,1,3,1,2,1,1,1,1,1,1,1,0.500000,0.500000,0,3,2
4,5,1,2,2,3,1,1,1,1,1,1,1,0.333333,0.400000,0,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142501,29,25,26,1,2,1,2,1,2,1,2,0,0.038462,0.103448,0,27,3
142502,29,25,26,1,3,1,1,1,1,1,1,1,0.038462,0.071429,0,26,3
142503,29,25,27,1,2,1,1,1,1,1,1,1,0.038462,0.100000,0,27,2
142504,29,25,26,2,3,1,1,1,1,1,1,1,0.038462,0.071429,0,26,3
142505,29,26,27,1,2,1,1,1,1,1,1,1,0.037037,0.068966,0,27,2

## Closed form expression for Maximum Rate

In [29]:
for T in range(4,20):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                 for b2 in range(a2+1,T):
                    if(a1>a2 and b1!=b2 and T >= b1 + b2  and a2!=1 and ((b2-a2)/a2)<(b1-a1)/a1):
#                         for k in range(1,int(max(a1,a2)*min((T-b2+1-a1)/b1,(T-b1+1-a2)/b2))+1):
                        for k in range(a2+1,T):
                            if(k>=a2):
                                temp_max = -100
                                temp_ind_last = -100
                                temp_ind_first = -100 
                                N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
                                N2 = (k+a2-1)+(b2-a2)*math.floor((k+a2-1)/a2)+1
                                if(N1<=T-b2+1) and (N2<=T-b1+1):
                                    for t in range(0,k):
                                        temp = (b2-a2)*math.floor((t)/a2)-(b1-a1)*math.floor((t)/a1)
                                        temp1 = temp
                                        if temp1>=temp_max:
                                            temp_ind_last = t
                                        if temp1>temp_max:
                                            temp_ind_first = t
                                            temp_max= temp
#                                     if(temp_ind_last!=(k-1) and temp_ind_first%(a2*math.floor(a1/a2))!=0 and  temp_ind_first%(a1-a2)!=0 and temp_ind_first%(a1)!=0):
#                                     if(temp_ind_first%(a2)!=0):
                                    if a1%a2!=0:
                                        if(temp_ind_first!=a2*math.floor(min((k-1),a1)/a2)):
                                            ds1=del_spec(a1,b1,N1-1,k,k+a1)
                                            ds2=del_spec(a2,b2,N2-1,k,k+a2)
                                            print(k,temp_ind_first,temp_ind_last,T,a1,b1,a2,b2)
                                            print(ds1)
                                            print(ds2)
                                    elif a1%a2==0:
                                        if(temp_ind_first!=(a2)*math.floor((min((k-1),a1)/a2)-1) and temp_ind_first!=(a2)*math.floor(min((k-1),a1)/a2) ):
                                            ds1=del_spec(a1,b1,N1-1,k,k+a1)
                                            ds2=del_spec(a2,b2,N2-1,k,k+a2)
                                            print(k,temp_ind_first,temp_ind_last,T,a1,b1,a2,b2)
                                            print(ds1)
                                            print(ds2)

In [26]:
def SDE_max_rate(T,a1,b1,a2,b2):
    return df_m[(df_m["T"]==T)&(df_m["a1"]==a1)&(df_m["b1"]==b1)&(df_m["a2"]==a2)&(df_m["b2"]==b2)].reset_index()["R_max"].iloc[0]
def opt_rate(T,a1,b1,a2,b2):
    return df_m[(df_m["T"]==T)&(df_m["a1"]==a1)&(df_m["b1"]==b1)&(df_m["a2"]==a2)&(df_m["b2"]==b2)].reset_index()["R_opt"].iloc[0]

# GSDE

In [27]:
def sgn(x):
    if x>0: return 1
    elif x==0: return 1
    else: return -1

def disp_vect(N,a,b,g,t):
    dv = [0]*(N)    
    for i in range(0,N):
        if((i+1)%b == 1):
            dv[i] = g
        else:
            dv[i] = t
    return dv
    
def ds_value (t,N,k,dv):
    temp = N - 1
    for j in range(0,N):
        sum_temp = 0
        for l in range (0,j+1):
            sum_temp = sum_temp + dv[l]
#         print(t,j,sum_temp)
        temp = temp-(1+sgn(t-sum_temp))/2
    return temp 
    
def del_spec_GSDE(N,k,dv):
    ds = [0]*(k)   
    for t in range(0,k):
        ds[t] = ds_value(t,N,k,dv)
    return ds

In [28]:
sgn(0)

1

In [29]:
T = 21
a1 = 6 
b1 = 7 
a2 = 6
b2 = 7
#                   Delay Constraint 
T1 = T-b2
T2 = T-b1

#                   Dispersion Span          
N1 = T1+1
N2 = T2+1

#                   Ti+1 = mi*bi+di
m1 = math.floor((T1+1)/b1)
d1 = int((T1+1)%b1)
m2 = math.floor((T2+1)/b2)
d2 = int((T2+1)%b2) 

#                   Parameters for dispersion vector                     
t1 = int(lcm(b1-a1,m1)/(b1-a1))
g1 = int(t1*(1+(b1-a1)/m1))
t2 = int(lcm(b2-a2,m2)/(b2-a2))
g2 = int(t2*(1+(b2-a2)/m2))

#                   Code length and redundancy                     
n1 = int(t1*(m1*b1+(m1+1)*(b1-a1)/m1+d1))
r1 = int(t1*(b1+(b1-a1)/m1))
n2 = int(t2*(m2*b2+(m2+1)*(b2-a2)/m2+d2))
r2 = int(t2*(b2+(b2-a2)/m2))

k1=n1-r1
k2=n2-r2

#                   Dispersion vector  
dv1 = disp_vect(N1,a1,b1,g1,t1)
dv2 = disp_vect(N2,a2,b2,g2,t2)

#                   Delay Spectrum           
ds1 = del_spec_GSDE(N1,n1-r1,dv1)
ds2 = del_spec_GSDE(N2,n2-r2,dv2)
R_GSDE = min(k1/n1,k2/n2)

In [30]:
n1

33

In [31]:
k2

18

In [32]:
m1

2

In [33]:
dv1

[3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3]

In [34]:
ds1

[14.0,
 14.0,
 14.0,
 13.0,
 13.0,
 12.0,
 12.0,
 11.0,
 11.0,
 10.0,
 10.0,
 9.0,
 9.0,
 8.0,
 8.0,
 7.0,
 7.0,
 7.0]

In [35]:
ds2

[14.0,
 14.0,
 14.0,
 13.0,
 13.0,
 12.0,
 12.0,
 11.0,
 11.0,
 10.0,
 10.0,
 9.0,
 9.0,
 8.0,
 8.0,
 7.0,
 7.0,
 7.0]

In [36]:
R_GSDE

0.5454545454545454

In [37]:
cnt = 0 
cnt1 = 0 
cnt2 = 0 
for T in range(4,30):
    for a1 in range(1,T):
        for a2 in range(1,T):
            for b1 in range(a1+1,T):
                for b2 in range(a2+1,T):
                    if (T>=b1+b2):
                    
    #                   Delay Constraint 
                        T1 = T-b2
                        T2 = T-b1

    #                   Dispersion Span          
                        N1 = T1+1
                        N2 = T2+1

    #                   Ti+1 = mi*bi+di
                        m1 = math.floor((T1+1)/b1)
                        d1 = int((T1+1)%b1)
                        m2 = math.floor((T2+1)/b2)
                        d2 = int((T2+1)%b2) 

    #                   Parameters for dispersion vector                     
                        t1 = int(lcm(b1-a1,m1)/(b1-a1))
                        g1 = int(t1*(1+(b1-a1)/m1))
                        t2 = int(lcm(b2-a2,m2)/(b2-a2))
                        g2 = int(t2*(1+(b2-a2)/m2))

    #                   Code length and redundancy                     
                        n1 = int(t1*(m1*b1+(m1+1)*(b1-a1)/m1+d1))
                        r1 = int(t1*(b1+(b1-a1)/m1))
                        n2 = int(t2*(m2*b2+(m2+1)*(b2-a2)/m2+d2))
                        r2 = int(t2*(b2+(b2-a2)/m2))
                        
                        k1=n1-r1
                        k2=n2-r2
                    
    #                   Dispersion vector  
                        dv1 = disp_vect(N1,a1,b1,g1,t1)
                        dv2 = disp_vect(N2,a2,b2,g2,t2)
                    
    #                   Delay Spectrum           
                        ds1 = del_spec_GSDE(N1,n1-r1,dv1)
                        ds2 = del_spec_GSDE(N2,n2-r2,dv2)
                        cnt+=1 
                        if k1==k2 and max(ds1+np.flip(ds2)) <= T and a1>(m1+1)*d1 and a2>(m2+1*d2) and d1!=0 and d2!=0 and m1==m2 and m1!=1:
                            cnt1+=1 
                            R_GSDE = min(k1/n1,k2/n2)
                            R_SDE = SDE_max_rate(T,a1,b1,a2,b2)
                            R_opt = opt_rate(T,a1,b1,a2,b2)
                            if(R_SDE < R_GSDE):
                                cnt2+=1 
                                print(T,a1,b1,a2,b2,R_SDE,R_GSDE,R_opt)

15 4 5 4 5 0.5 0.56 0.5833333333333334
18 4 6 4 6 0.5 0.5625 0.6
18 5 6 5 6 0.5 0.5517241379310345 0.5714285714285714
21 4 7 4 7 0.5 0.5641025641025641 0.6111111111111112
21 5 7 5 7 0.5 0.5555555555555556 0.5882352941176471
21 6 7 6 7 0.5 0.5454545454545454 0.5625
24 4 8 4 8 0.5 0.5652173913043478 0.6190476190476191
24 5 6 5 6 0.6666666666666666 0.6885245901639344 0.7
24 5 8 5 8 0.5 0.5581395348837209 0.6
24 6 8 6 8 0.5 0.55 0.5789473684210527
24 7 8 7 8 0.5 0.5405405405405406 0.5555555555555556
27 4 9 4 9 0.5 0.5660377358490566 0.625
27 5 9 5 9 0.5 0.56 0.6086956521739131
27 6 9 6 9 0.5 0.5531914893617021 0.5909090909090909
27 7 9 7 9 0.5 0.5454545454545454 0.5714285714285714
27 8 9 8 9 0.5 0.5365853658536586 0.55
28 5 7 5 7 0.6666666666666666 0.6891891891891891 0.7083333333333334
28 6 7 6 7 0.6666666666666666 0.6857142857142857 0.6956521739130435

In [38]:
cnt

142506

In [39]:
cnt1

18

In [40]:
cnt2

18

## Channel 1 - SDE and Channel  2 - GSDE

In [146]:
cnt = 0 
cnt1 = 0 
cnt2 = 0 
valid = set()
for lam in range(0,3):
    for T in range(4,20):
        for a1 in range(1,T):
            for a2 in range(1,T):
                for b1 in range(a1+1,T):
                    for b2 in range(a2+1,T):
                        if (T>=b1+b2):
                            T1 = T-b2
                            T2 = T-b1-lam
                            if m2>=1:
                                d2 = int((T2+1)%b2) 
                                t2 = int(lcm(b2-a2,m2)/(b2-a2))
                                g2 = int(t2*(1+(b2-a2)/m2))
                                n2 = int(t2*(m2*b2+(m2+1)*(b2-a2)/m2+d2))
                                r2 = int(t2*(b2+(b2-a2)/m2))
                                k2= n2-r2
                                k = k2
        #                         print(k)
                                N1 = (k+a1-1)+(b1-a1)*math.floor((k+a1-1)/a1)+1
                                if N1<=T1+1 :
        #                             print(N1)
                                    ds1= del_spec(a1,b1,N1-1,k,k+a1)[0:k]
                                    N2 = T2+1
                                    dv2 = disp_vect(N2,a2,b2,g2,t2)         
                                    ds2 = del_spec_GSDE(N2,k,dv2)
                                    cnt+=1 
        #                             print(k,ds1,ds2,T,a1,b1,a2,b2,k,n2)
        #                         if(k+a1>n2):    
                                    if max(ds1+np.flip(ds2)) <= T :
                                        cnt1+=1 
                                        R_con = min(k/(k+a1),k/n2)
                                        R_SDE = SDE_max_rate(T,a1,b1,a2,b2)
                                        R_opt = opt_rate(T,a1,b1,a2,b2)
                                        if(R_SDE < R_con):
                                            cnt2+=1 
                                            print(T,a1,b1,a2,b2,R_SDE,R_con,R_opt) 
                                            valid.add((T,a1,a2,b1,b2))

6 2 3 1 2 0.3333333333333333 0.4 0.5
7 2 4 1 2 0.3333333333333333 0.4 0.5
7 3 4 1 2 0.25 0.4 0.42857142857142855
8 2 5 1 2 0.3333333333333333 0.4 0.5
8 3 5 1 2 0.25 0.4 0.4444444444444444
8 4 5 1 2 0.2 0.3333333333333333 0.375
9 2 6 1 2 0.3333333333333333 0.4 0.5
9 3 6 1 2 0.25 0.4 0.45454545454545453
9 3 4 2 3 0.4 0.42857142857142855 0.5
9 4 6 1 2 0.2 0.3333333333333333 0.4
9 5 6 1 2 0.16666666666666666 0.2857142857142857 0.3333333333333333
10 2 7 1 2 0.3333333333333333 0.4 0.5
10 3 7 1 2 0.25 0.4 0.46153846153846156
10 3 5 2 3 0.4 0.42857142857142855 0.5
10 4 7 1 2 0.2 0.3333333333333333 0.4166666666666667
10 4 5 2 3 0.3333333333333333 0.42857142857142855 0.4444444444444444
10 5 7 1 2 0.16666666666666666 0.2857142857142857 0.36363636363636365
10 6 7 1 2 0.14285714285714285 0.25 0.3
11 2 8 1 2 0.3333333333333333 0.4 0.5
11 3 8 1 2 0.25 0.4 0.4666666666666667
11 3 6 2 3 0.4 0.42857142857142855 0.5
11 4 8 1 2 0.2 0.3333333333333333 0.42857142857142855
11 4 6 2 3 0.3333333333333333 0.42857142857142855 0.45454545454545453
11 5 8 1 2 0.16666666666666666 0.2857142857142857 0.38461538461538464
11 5 6 2 3 0.2857142857142857 0.375 0.4
11 6 8 1 2 0.14285714285714285 0.25 0.3333333333333333
11 7 8 1 2 0.125 0.2222222222222222 0.2727272727272727
12 2 9 1 2 0.3333333333333333 0.4 0.5
12 3 9 1 2 0.25 0.4 0.47058823529411764
12 3 7 2 3 0.4 0.42857142857142855 0.5
12 4 9 1 2 0.2 0.3333333333333333 0.4375
12 4 7 2 3 0.3333333333333333 0.42857142857142855 0.46153846153846156
12 4 5 3 4 0.42857142857142855 0.4444444444444444 0.5
12 5 9 1 2 0.16666666666666666 0.2857142857142857 0.4
12 5 7 2 3 0.2857142857142857 0.375 0.4166666666666667
12 6 9 1 2 0.14285714285714285 0.25 0.35714285714285715
12 6 7 2 3 0.25 0.3333333333333333 0.36363636363636365
12 7 9 1 2 0.125 0.2222222222222222 0.3076923076923077
12 8 9 1 2 0.1111111111111111 0.2 0.25
13 2 10 1 2 0.3333333333333333 0.4 0.5
13 3 10 1 2 0.25 0.4 0.47368421052631576
13 3 8 2 3 0.4 0.42857142857142855 0.5
13 4 10 1 2 0.2 0.3333333333333333 0.4444444444444444
13 4 8 2 3 0.3333333333333333 0.42857142857142855 0.4666666666666667
13 4 6 3 4 0.42857142857142855 0.4444444444444444 0.5
13 5 10 1 2 0.16666666666666666 0.2857142857142857 0.4117647058823529
13 5 8 2 3 0.2857142857142857 0.375 0.42857142857142855
13 5 6 3 4 0.375 0.4444444444444444 0.45454545454545453
13 6 10 1 2 0.14285714285714285 0.25 0.375
13 6 8 2 3 0.25 0.3333333333333333 0.38461538461538464
13 7 10 1 2 0.125 0.2222222222222222 0.3333333333333333
13 7 8 2 3 0.2222222222222222 0.3 0.3333333333333333
13 8 10 1 2 0.1111111111111111 0.2 0.2857142857142857
13 9 10 1 2 0.1 0.18181818181818182 0.23076923076923078
14 2 11 1 2 0.3333333333333333 0.4 0.5
14 3 11 1 2 0.25 0.4 0.47619047619047616
14 3 9 2 3 0.4 0.42857142857142855 0.5
14 4 11 1 2 0.2 0.3333333333333333 0.45
14 4 9 2 3 0.3333333333333333 0.42857142857142855 0.47058823529411764
14 4 7 3 4 0.42857142857142855 0.4444444444444444 0.5
14 5 11 1 2 0.16666666666666666 0.2857142857142857 0.42105263157894735
14 5 9 2 3 0.2857142857142857 0.375 0.4375
14 5 7 3 4 0.375 0.4444444444444444 0.46153846153846156
14 6 11 1 2 0.14285714285714285 0.25 0.3888888888888889
14 6 9 2 3 0.25 0.3333333333333333 0.4
14 6 7 3 4 0.3333333333333333 0.4 0.4166666666666667
14 7 11 1 2 0.125 0.2222222222222222 0.35294117647058826
14 7 9 2 3 0.2222222222222222 0.3 0.35714285714285715
14 8 11 1 2 0.1111111111111111 0.2 0.3125
14 8 9 2 3 0.2 0.2727272727272727 0.3076923076923077
14 9 11 1 2 0.1 0.18181818181818182 0.26666666666666666
14 10 11 1 2 0.09090909090909091 0.16666666666666666 0.21428571428571427
15 2 12 1 2 0.3333333333333333 0.4 0.5
15 3 12 1 2 0.25 0.4 0.4782608695652174
15 3 10 2 3 0.4 0.42857142857142855 0.5
15 4 12 1 2 0.2 0.3333333333333333 0.45454545454545453
15 4 10 2 3 0.3333333333333333 0.42857142857142855 0.47368421052631576
15 4 8 3 4 0.42857142857142855 0.4444444444444444 0.5
15 5 12 1 2 0.16666666666666666 0.2857142857142857 0.42857142857142855
15 5 10 2 3 0.2857142857142857 0.375 0.4444444444444444
15 5 8 3 4 0.375 0.4444444444444444 0.4666666666666667
15 5 6 4 5 0.4444444444444444 0.45454545454545453 0.5
15 6 12 1 2 0.14285714285714285 0.25 0.4
15 6 10 2 3 0.25 0.3333333333333333 0.4117647058823529
15 6 8 3 4 0.3333333333333333 0.4 0.42857142857142855
15 7 12 1 2 0.125 0.2222222222222222 0.3684210526315789
15 7 10 2 3 0.2222222222222222 0.3 0.375
15 7 8 3 4 0.3 0.36363636363636365 0.38461538461538464
15 8 12 1 2 0.1111111111111111 0.2 0.3333333333333333
15 8 10 2 3 0.2 0.2727272727272727 0.3333333333333333
15 9 12 1 2 0.1 0.18181818181818182 0.29411764705882354
15 9 10 2 3 0.18181818181818182 0.25 0.2857142857142857
15 10 12 1 2 0.09090909090909091 0.16666666666666666 0.25
15 11 12 1 2 0.08333333333333333 0.15384615384615385 0.2
16 2 13 1 2 0.3333333333333333 0.4 0.5
16 3 13 1 2 0.25 0.4 0.48
16 3 11 2 3 0.4 0.42857142857142855 0.5
16 4 13 1 2 0.2 0.3333333333333333 0.4583333333333333
16 4 11 2 3 0.3333333333333333 0.42857142857142855 0.47619047619047616
16 4 9 3 4 0.42857142857142855 0.4444444444444444 0.5
16 5 13 1 2 0.16666666666666666 0.2857142857142857 0.43478260869565216
16 5 11 2 3 0.2857142857142857 0.375 0.45
16 5 9 3 4 0.375 0.4444444444444444 0.47058823529411764
16 5 7 4 5 0.4444444444444444 0.45454545454545453 0.5
16 6 13 1 2 0.14285714285714285 0.25 0.4090909090909091
16 6 11 2 3 0.25 0.3333333333333333 0.42105263157894735
16 6 9 3 4 0.3333333333333333 0.4 0.4375
16 6 7 4 5 0.4 0.45454545454545453 0.46153846153846156
16 7 13 1 2 0.125 0.2222222222222222 0.38095238095238093
16 7 11 2 3 0.2222222222222222 0.3 0.3888888888888889
16 7 9 3 4 0.3 0.36363636363636365 0.4
16 8 13 1 2 0.1111111111111111 0.2 0.35
16 8 11 2 3 0.2 0.2727272727272727 0.35294117647058826
16 8 9 3 4 0.2727272727272727 0.3333333333333333 0.35714285714285715
16 9 13 1 2 0.1 0.18181818181818182 0.3157894736842105
16 9 11 2 3 0.18181818181818182 0.25 0.3125
16 10 13 1 2 0.09090909090909091 0.16666666666666666 0.2777777777777778
16 10 11 2 3 0.16666666666666666 0.23076923076923078 0.26666666666666666
16 11 13 1 2 0.08333333333333333 0.15384615384615385 0.23529411764705882
16 12 13 1 2 0.07692307692307693 0.14285714285714285 0.1875
17 2 14 1 2 0.3333333333333333 0.4 0.5
17 3 14 1 2 0.25 0.4 0.48148148148148145
17 3 12 2 3 0.4 0.42857142857142855 0.5
17 4 14 1 2 0.2 0.3333333333333333 0.46153846153846156
17 4 12 2 3 0.3333333333333333 0.42857142857142855 0.4782608695652174
17 4 10 3 4 0.42857142857142855 0.4444444444444444 0.5
17 5 14 1 2 0.16666666666666666 0.2857142857142857 0.44
17 5 12 2 3 0.2857142857142857 0.375 0.45454545454545453
17 5 10 3 4 0.375 0.4444444444444444 0.47368421052631576
17 5 8 4 5 0.4444444444444444 0.45454545454545453 0.5
17 6 14 1 2 0.14285714285714285 0.25 0.4166666666666667
17 6 12 2 3 0.25 0.3333333333333333 0.42857142857142855
17 6 10 3 4 0.3333333333333333 0.4 0.4444444444444444
17 6 8 4 5 0.4 0.45454545454545453 0.4666666666666667
17 7 14 1 2 0.125 0.2222222222222222 0.391304347826087
17 7 12 2 3 0.2222222222222222 0.3 0.4
17 7 10 3 4 0.3 0.36363636363636365 0.4117647058823529
17 7 8 4 5 0.36363636363636365 0.4166666666666667 0.42857142857142855
17 8 14 1 2 0.1111111111111111 0.2 0.36363636363636365
17 8 12 2 3 0.2 0.2727272727272727 0.3684210526315789
17 8 10 3 4 0.2727272727272727 0.3333333333333333 0.375
17 9 14 1 2 0.1 0.18181818181818182 0.3333333333333333
17 9 12 2 3 0.18181818181818182 0.25 0.3333333333333333
17 9 10 3 4 0.25 0.3076923076923077 0.3333333333333333
17 10 14 1 2 0.09090909090909091 0.16666666666666666 0.3
17 10 12 2 3 0.16666666666666666 0.23076923076923078 0.29411764705882354
17 11 14 1 2 0.08333333333333333 0.15384615384615385 0.2631578947368421
17 11 12 2 3 0.15384615384615385 0.21428571428571427 0.25
17 12 14 1 2 0.07692307692307693 0.14285714285714285 0.2222222222222222
17 13 14 1 2 0.07142857142857142 0.13333333333333333 0.17647058823529413
18 2 15 1 2 0.3333333333333333 0.4 0.5
18 3 15 1 2 0.25 0.4 0.4827586206896552
18 3 13 2 3 0.4 0.42857142857142855 0.5
18 4 15 1 2 0.2 0.3333333333333333 0.4642857142857143
18 4 13 2 3 0.3333333333333333 0.42857142857142855 0.48
18 4 11 3 4 0.42857142857142855 0.4444444444444444 0.5
18 5 15 1 2 0.16666666666666666 0.2857142857142857 0.4444444444444444
18 5 13 2 3 0.2857142857142857 0.375 0.4583333333333333
18 5 11 3 4 0.375 0.4444444444444444 0.47619047619047616
18 5 9 4 5 0.4444444444444444 0.45454545454545453 0.5

18 6 15 1 2 0.14285714285714285 0.25 0.4230769230769231
18 6 13 2 3 0.25 0.3333333333333333 0.43478260869565216
18 6 11 3 4 0.3333333333333333 0.4 0.45
18 6 9 4 5 0.4 0.45454545454545453 0.47058823529411764
18 6 7 5 6 0.45454545454545453 0.46153846153846156 0.5
18 7 15 1 2 0.125 0.2222222222222222 0.4
18 7 13 2 3 0.2222222222222222 0.3 0.4090909090909091
18 7 11 3 4 0.3 0.36363636363636365 0.42105263157894735
18 7 9 4 5 0.36363636363636365 0.4166666666666667 0.4375
18 8 15 1 2 0.1111111111111111 0.2 0.375
18 8 13 2 3 0.2 0.2727272727272727 0.38095238095238093
18 8 11 3 4 0.2727272727272727 0.3333333333333333 0.3888888888888889
18 8 9 4 5 0.3333333333333333 0.38461538461538464 0.4
18 9 15 1 2 0.1 0.18181818181818182 0.34782608695652173
18 9 13 2 3 0.18181818181818182 0.25 0.35
18 9 11 3 4 0.25 0.3076923076923077 0.35294117647058826
18 10 15 1 2 0.09090909090909091 0.16666666666666666 0.3181818181818182
18 10 13 2 3 0.16666666666666666 0.23076923076923078 0.3157894736842105
18 10 11 3 4 0.23076923076923078 0.2857142857142857 0.3125
18 11 15 1 2 0.08333333333333333 0.15384615384615385 0.2857142857142857
18 11 13 2 3 0.15384615384615385 0.21428571428571427 0.2777777777777778
18 12 15 1 2 0.07692307692307693 0.14285714285714285 0.25
18 12 13 2 3 0.14285714285714285 0.2 0.23529411764705882
18 13 15 1 2 0.07142857142857142 0.13333333333333333 0.21052631578947367
18 14 15 1 2 0.06666666666666667 0.125 0.16666666666666666
19 2 16 1 2 0.3333333333333333 0.4 0.5
19 3 16 1 2 0.25 0.4 0.4838709677419355
19 3 14 2 3 0.4 0.42857142857142855 0.5
19 4 16 1 2 0.2 0.3333333333333333 0.4666666666666667
19 4 14 2 3 0.3333333333333333 0.42857142857142855 0.48148148148148145
19 4 12 3 4 0.42857142857142855 0.4444444444444444 0.5
19 5 16 1 2 0.16666666666666666 0.2857142857142857 0.4482758620689655
19 5 14 2 3 0.2857142857142857 0.375 0.46153846153846156
19 5 12 3 4 0.375 0.4444444444444444 0.4782608695652174
19 5 10 4 5 0.4444444444444444 0.45454545454545453 0.5
19 6 16 1 2 0.14285714285714285 0.25 0.42857142857142855
19 6 14 2 3 0.25 0.3333333333333333 0.44
19 6 12 3 4 0.3333333333333333 0.4 0.45454545454545453
19 6 10 4 5 0.4 0.45454545454545453 0.47368421052631576
19 6 8 5 6 0.45454545454545453 0.46153846153846156 0.5
19 7 16 1 2 0.125 0.2222222222222222 0.4074074074074074
19 7 14 2 3 0.2222222222222222 0.3 0.4166666666666667
19 7 12 3 4 0.3 0.36363636363636365 0.42857142857142855
19 7 10 4 5 0.36363636363636365 0.4166666666666667 0.4444444444444444
19 7 8 5 6 0.4166666666666667 0.46153846153846156 0.4666666666666667
19 8 16 1 2 0.1111111111111111 0.2 0.38461538461538464
19 8 14 2 3 0.2 0.2727272727272727 0.391304347826087
19 8 12 3 4 0.2727272727272727 0.3333333333333333 0.4
19 8 10 4 5 0.3333333333333333 0.38461538461538464 0.4117647058823529
19 9 16 1 2 0.1 0.18181818181818182 0.36
19 9 14 2 3 0.18181818181818182 0.25 0.36363636363636365
19 9 12 3 4 0.25 0.3076923076923077 0.3684210526315789
19 9 10 4 5 0.3076923076923077 0.35714285714285715 0.375
19 10 16 1 2 0.09090909090909091 0.16666666666666666 0.3333333333333333
19 10 14 2 3 0.16666666666666666 0.23076923076923078 0.3333333333333333
19 10 12 3 4 0.23076923076923078 0.2857142857142857 0.3333333333333333
19 11 16 1 2 0.08333333333333333 0.15384615384615385 0.30434782608695654
19 11 14 2 3 0.15384615384615385 0.21428571428571427 0.3
19 11 12 3 4 0.21428571428571427 0.26666666666666666 0.29411764705882354
19 12 16 1 2 0.07692307692307693 0.14285714285714285 0.2727272727272727
19 12 14 2 3 0.14285714285714285 0.2 0.2631578947368421
19 13 16 1 2 0.07142857142857142 0.13333333333333333 0.23809523809523808
19 13 14 2 3 0.13333333333333333 0.1875 0.2222222222222222
19 14 16 1 2 0.06666666666666667 0.125 0.2
19 15 16 1 2 0.0625 0.11764705882352941 0.15789473684210525
8 3 4 1 3 0.25 0.2857142857142857 0.42857142857142855
9 3 4 1 3 0.25 0.375 0.5
9 3 5 1 3 0.25 0.2857142857142857 0.4444444444444444
9 4 5 1 3 0.2 0.2857142857142857 0.375
10 3 5 1 3 0.25 0.375 0.5
10 3 6 1 3 0.25 0.2857142857142857 0.45454545454545453
10 4 5 1 3 0.2 0.375 0.4444444444444444
10 4 6 1 3 0.2 0.2857142857142857 0.4
10 5 6 1 3 0.16666666666666666 0.2857142857142857 0.3333333333333333
11 3 6 1 3 0.25 0.375 0.5
11 3 7 1 3 0.25 0.2857142857142857 0.46153846153846156
11 4 5 1 3 0.3333333333333333 0.4444444444444444 0.5
11 4 6 1 3 0.2 0.375 0.45454545454545453
11 4 7 1 3 0.2 0.2857142857142857 0.4166666666666667
11 5 6 1 3 0.16666666666666666 0.375 0.4
11 5 7 1 3 0.16666666666666666 0.2857142857142857 0.36363636363636365
11 6 7 1 3 0.14285714285714285 0.25 0.3
12 3 7 1 3 0.25 0.375 0.5
12 3 8 1 3 0.25 0.2857142857142857 0.4666666666666667
12 4 6 1 3 0.3333333333333333 0.4444444444444444 0.5
12 4 7 1 3 0.2 0.375 0.46153846153846156
12 4 8 1 3 0.2 0.2857142857142857 0.42857142857142855
12 4 5 2 4 0.3333333333333333 0.4 0.5
12 5 6 1 3 0.2857142857142857 0.4444444444444444 0.45454545454545453
12 5 7 1 3 0.16666666666666666 0.375 0.4166666666666667
12 5 8 1 3 0.16666666666666666 0.2857142857142857 0.38461538461538464
12 5 6 2 4 0.2857142857142857 0.3333333333333333 0.4
12 6 7 1 3 0.14285714285714285 0.3333333333333333 0.36363636363636365
12 6 8 1 3 0.14285714285714285 0.25 0.3333333333333333
12 7 8 1 3 0.125 0.2222222222222222 0.2727272727272727
13 3 8 1 3 0.25 0.375 0.5
13 3 9 1 3 0.25 0.2857142857142857 0.47058823529411764
13 4 5 1 3 0.3333333333333333 0.375 0.5833333333333334
13 4 7 1 3 0.3333333333333333 0.4444444444444444 0.5
13 4 8 1 3 0.2 0.375 0.4666666666666667
13 4 9 1 3 0.2 0.2857142857142857 0.4375
13 4 6 2 4 0.3333333333333333 0.4 0.5
13 5 7 1 3 0.2857142857142857 0.4444444444444444 0.46153846153846156
13 5 8 1 3 0.16666666666666666 0.375 0.42857142857142855
13 5 9 1 3 0.16666666666666666 0.2857142857142857 0.4
13 5 6 2 4 0.2857142857142857 0.4 0.45454545454545453
13 5 7 2 4 0.2857142857142857 0.3333333333333333 0.4166666666666667
13 6 7 1 3 0.25 0.4 0.4166666666666667
13 6 8 1 3 0.14285714285714285 0.3333333333333333 0.38461538461538464
13 6 9 1 3 0.14285714285714285 0.25 0.35714285714285715
13 6 7 2 4 0.25 0.3333333333333333 0.36363636363636365
13 7 8 1 3 0.125 0.3 0.3333333333333333
13 7 9 1 3 0.125 0.2222222222222222 0.3076923076923077
13 8 9 1 3 0.1111111111111111 0.2 0.25
14 3 9 1 3 0.25 0.375 0.5
14 3 10 1 3 0.25 0.2857142857142857 0.47368421052631576
14 4 5 1 3 0.42857142857142855 0.4444444444444444 0.6153846153846154
14 4 6 1 3 0.3333333333333333 0.375 0.5714285714285714
14 4 8 1 3 0.3333333333333333 0.4444444444444444 0.5
14 4 9 1 3 0.2 0.375 0.47058823529411764
14 4 10 1 3 0.2 0.2857142857142857 0.4444444444444444
14 4 7 2 4 0.3333333333333333 0.4 0.5
14 5 6 1 3 0.2857142857142857 0.375 0.5384615384615384
14 5 8 1 3 0.2857142857142857 0.4444444444444444 0.4666666666666667
14 5 9 1 3 0.16666666666666666 0.375 0.4375
14 5 10 1 3 0.16666666666666666 0.2857142857142857 0.4117647058823529
14 5 6 2 4 0.375 0.45454545454545453 0.5
14 5 7 2 4 0.2857142857142857 0.4 0.46153846153846156
14 5 8 2 4 0.2857142857142857 0.3333333333333333 0.42857142857142855
14 6 8 1 3 0.25 0.4 0.42857142857142855
14 6 9 1 3 0.14285714285714285 0.3333333333333333 0.4
14 6 10 1 3 0.14285714285714285 0.25 0.375
14 6 7 2 4 0.25 0.4 0.4166666666666667
14 6 8 2 4 0.25 0.3333333333333333 0.38461538461538464
14 7 8 1 3 0.2222222222222222 0.36363636363636365 0.38461538461538464
14 7 9 1 3 0.125 0.3 0.35714285714285715
14 7 10 1 3 0.125 0.2222222222222222 0.3333333333333333
14 7 8 2 4 0.2222222222222222 0.3 0.3333333333333333
14 8 9 1 3 0.1111111111111111 0.2727272727272727 0.3076923076923077
14 8 10 1 3 0.1111111111111111 0.2 0.2857142857142857
14 9 10 1 3 0.1 0.18181818181818182 0.23076923076923078
15 3 10 1 3 0.25 0.375 0.5
15 3 11 1 3 0.25 0.2857142857142857 0.47619047619047616
15 4 6 1 3 0.42857142857142855 0.4444444444444444 0.6
15 4 7 1 3 0.3333333333333333 0.375 0.5625
15 4 9 1 3 0.3333333333333333 0.4444444444444444 0.5
15 4 10 1 3 0.2 0.375 0.47368421052631576
15 4 11 1 3 0.2 0.2857142857142857 0.45
15 4 8 2 4 0.3333333333333333 0.4 0.5
15 5 6 1 3 0.375 0.4444444444444444 0.5714285714285714
15 5 6 1 4 0.2857142857142857 0.3 0.5384615384615384
15 5 7 1 3 0.2857142857142857 0.375 0.5333333333333333
15 5 9 1 3 0.2857142857142857 0.4444444444444444 0.47058823529411764
15 5 10 1 3 0.16666666666666666 0.375 0.4444444444444444
15 5 11 1 3 0.16666666666666666 0.2857142857142857 0.42105263157894735
15 5 7 2 4 0.375 0.45454545454545453 0.5
15 5 8 2 4 0.2857142857142857 0.4 0.4666666666666667
15 5 9 2 4 0.2857142857142857 0.3333333333333333 0.4375
15 5 6 3 5 0.375 0.4166666666666667 0.5

15 6 7 1 3 0.25 0.3333333333333333 0.5
15 6 9 1 3 0.25 0.4 0.4375
15 6 10 1 3 0.14285714285714285 0.3333333333333333 0.4117647058823529
15 6 11 1 3 0.14285714285714285 0.25 0.3888888888888889
15 6 7 2 4 0.3333333333333333 0.45454545454545453 0.46153846153846156
15 6 8 2 4 0.25 0.4 0.42857142857142855
15 6 9 2 4 0.25 0.3333333333333333 0.4
15 6 7 3 5 0.3333333333333333 0.36363636363636365 0.4166666666666667
15 7 9 1 3 0.2222222222222222 0.36363636363636365 0.4
15 7 10 1 3 0.125 0.3 0.375
15 7 11 1 3 0.125 0.2222222222222222 0.35294117647058826
15 7 8 2 4 0.2222222222222222 0.36363636363636365 0.38461538461538464
15 7 9 2 4 0.2222222222222222 0.3 0.35714285714285715
15 8 9 1 3 0.2 0.3333333333333333 0.35714285714285715
15 8 10 1 3 0.1111111111111111 0.2727272727272727 0.3333333333333333
15 8 11 1 3 0.1111111111111111 0.2 0.3125
15 8 9 2 4 0.2 0.2727272727272727 0.3076923076923077
15 9 10 1 3 0.1 0.25 0.2857142857142857
15 9 11 1 3 0.1 0.18181818181818182 0.26666666666666666
15 10 11 1 3 0.09090909090909091 0.16666666666666666 0.21428571428571427
16 3 11 1 3 0.25 0.375 0.5
16 3 12 1 3 0.25 0.2857142857142857 0.4782608695652174
16 4 7 1 3 0.42857142857142855 0.4444444444444444 0.5882352941176471
16 4 8 1 3 0.3333333333333333 0.375 0.5555555555555556
16 4 10 1 3 0.3333333333333333 0.4444444444444444 0.5
16 4 11 1 3 0.2 0.375 0.47619047619047616
16 4 12 1 3 0.2 0.2857142857142857 0.45454545454545453
16 4 9 2 4 0.3333333333333333 0.4 0.5
16 5 7 1 3 0.375 0.4444444444444444 0.5625
16 5 7 1 4 0.2857142857142857 0.3 0.5333333333333333
16 5 8 1 3 0.2857142857142857 0.375 0.5294117647058824
16 5 10 1 3 0.2857142857142857 0.4444444444444444 0.47368421052631576
16 5 11 1 3 0.16666666666666666 0.375 0.45
16 5 12 1 3 0.16666666666666666 0.2857142857142857 0.42857142857142855
16 5 8 2 4 0.375 0.45454545454545453 0.5
16 5 9 2 4 0.2857142857142857 0.4 0.47058823529411764
16 5 10 2 4 0.2857142857142857 0.3333333333333333 0.4444444444444444
16 5 7 3 5 0.375 0.4166666666666667 0.5
16 6 7 1 3 0.3333333333333333 0.4 0.5333333333333333
16 6 7 1 4 0.25 0.3 0.5
16 6 8 1 3 0.25 0.3333333333333333 0.5
16 6 10 1 3 0.25 0.4 0.4444444444444444
16 6 11 1 3 0.14285714285714285 0.3333333333333333 0.42105263157894735
16 6 12 1 3 0.14285714285714285 0.25 0.4
16 6 8 2 4 0.3333333333333333 0.45454545454545453 0.4666666666666667
16 6 9 2 4 0.25 0.4 0.4375
16 6 10 2 4 0.25 0.3333333333333333 0.4117647058823529
16 6 7 3 5 0.3333333333333333 0.4166666666666667 0.46153846153846156
16 6 8 3 5 0.3333333333333333 0.36363636363636365 0.42857142857142855
16 7 8 1 3 0.2222222222222222 0.3 0.4666666666666667
16 7 10 1 3 0.2222222222222222 0.36363636363636365 0.4117647058823529
16 7 11 1 3 0.125 0.3 0.3888888888888889
16 7 12 1 3 0.125 0.2222222222222222 0.3684210526315789
16 7 8 2 4 0.3 0.4166666666666667 0.42857142857142855
16 7 9 2 4 0.2222222222222222 0.36363636363636365 0.4
16 7 10 2 4 0.2222222222222222 0.3 0.375
16 7 8 3 5 0.3 0.36363636363636365 0.38461538461538464
16 8 10 1 3 0.2 0.3333333333333333 0.375
16 8 11 1 3 0.1111111111111111 0.2727272727272727 0.35294117647058826
16 8 12 1 3 0.1111111111111111 0.2 0.3333333333333333
16 8 9 2 4 0.2 0.3333333333333333 0.35714285714285715
16 8 10 2 4 0.2 0.2727272727272727 0.3333333333333333
16 9 10 1 3 0.18181818181818182 0.3076923076923077 0.3333333333333333
16 9 11 1 3 0.1 0.25 0.3125
16 9 12 1 3 0.1 0.18181818181818182 0.29411764705882354
16 9 10 2 4 0.18181818181818182 0.25 0.2857142857142857
16 10 11 1 3 0.09090909090909091 0.23076923076923078 0.26666666666666666
16 10 12 1 3 0.09090909090909091 0.16666666666666666 0.25
16 11 12 1 3 0.08333333333333333 0.15384615384615385 0.2
17 3 12 1 3 0.25 0.375 0.5
17 3 13 1 3 0.25 0.2857142857142857 0.48
17 4 8 1 3 0.42857142857142855 0.4444444444444444 0.5789473684210527
17 4 9 1 3 0.3333333333333333 0.375 0.55
17 4 11 1 3 0.3333333333333333 0.4444444444444444 0.5
17 4 12 1 3 0.2 0.375 0.4782608695652174
17 4 13 1 3 0.2 0.2857142857142857 0.4583333333333333
17 4 10 2 4 0.3333333333333333 0.4 0.5
17 5 8 1 3 0.375 0.4444444444444444 0.5555555555555556
17 5 8 1 4 0.2857142857142857 0.3 0.5294117647058824
17 5 9 1 3 0.2857142857142857 0.375 0.5263157894736842
17 5 11 1 3 0.2857142857142857 0.4444444444444444 0.47619047619047616
17 5 12 1 3 0.16666666666666666 0.375 0.45454545454545453
17 5 13 1 3 0.16666666666666666 0.2857142857142857 0.43478260869565216
17 5 9 2 4 0.375 0.45454545454545453 0.5
17 5 10 2 4 0.2857142857142857 0.4 0.47368421052631576
17 5 11 2 4 0.2857142857142857 0.3333333333333333 0.45
17 5 8 3 5 0.375 0.4166666666666667 0.5
17 6 8 1 3 0.3333333333333333 0.4 0.5294117647058824
17 6 8 1 4 0.25 0.3 0.5
17 6 9 1 3 0.25 0.3333333333333333 0.5
17 6 11 1 3 0.25 0.4 0.45
17 6 12 1 3 0.14285714285714285 0.3333333333333333 0.42857142857142855
17 6 13 1 3 0.14285714285714285 0.25 0.4090909090909091
17 6 9 2 4 0.3333333333333333 0.45454545454545453 0.47058823529411764
17 6 10 2 4 0.25 0.4 0.4444444444444444
17 6 11 2 4 0.25 0.3333333333333333 0.42105263157894735
17 6 7 3 5 0.4 0.46153846153846156 0.5
17 6 8 3 5 0.3333333333333333 0.4166666666666667 0.4666666666666667
17 6 9 3 5 0.3333333333333333 0.36363636363636365 0.4375
17 7 8 1 3 0.3 0.36363636363636365 0.5
17 7 8 1 4 0.2222222222222222 0.3 0.4666666666666667
17 7 9 1 3 0.2222222222222222 0.3 0.47058823529411764
17 7 11 1 3 0.2222222222222222 0.36363636363636365 0.42105263157894735
17 7 12 1 3 0.125 0.3 0.4
17 7 13 1 3 0.125 0.2222222222222222 0.38095238095238093
17 7 9 2 4 0.3 0.4166666666666667 0.4375
17 7 10 2 4 0.2222222222222222 0.36363636363636365 0.4117647058823529
17 7 11 2 4 0.2222222222222222 0.3 0.3888888888888889
17 7 8 3 5 0.3 0.4166666666666667 0.42857142857142855
17 7 9 3 5 0.3 0.36363636363636365 0.4
17 8 9 1 3 0.2 0.2727272727272727 0.4375
17 8 11 1 3 0.2 0.3333333333333333 0.3888888888888889
17 8 12 1 3 0.1111111111111111 0.2727272727272727 0.3684210526315789
17 8 13 1 3 0.1111111111111111 0.2 0.35
17 8 9 2 4 0.2727272727272727 0.38461538461538464 0.4
17 8 10 2 4 0.2 0.3333333333333333 0.375
17 8 11 2 4 0.2 0.2727272727272727 0.35294117647058826
17 8 9 3 5 0.2727272727272727 0.3333333333333333 0.35714285714285715
17 9 11 1 3 0.18181818181818182 0.3076923076923077 0.35294117647058826
17 9 12 1 3 0.1 0.25 0.3333333333333333
17 9 13 1 3 0.1 0.18181818181818182 0.3157894736842105
17 9 10 2 4 0.18181818181818182 0.3076923076923077 0.3333333333333333
17 9 11 2 4 0.18181818181818182 0.25 0.3125
17 10 11 1 3 0.16666666666666666 0.2857142857142857 0.3125
17 10 12 1 3 0.09090909090909091 0.23076923076923078 0.29411764705882354
17 10 13 1 3 0.09090909090909091 0.16666666666666666 0.2777777777777778
17 10 11 2 4 0.16666666666666666 0.23076923076923078 0.26666666666666666
17 11 12 1 3 0.08333333333333333 0.21428571428571427 0.25
17 11 13 1 3 0.08333333333333333 0.15384615384615385 0.23529411764705882
17 12 13 1 3 0.07692307692307693 0.14285714285714285 0.1875
18 3 13 1 3 0.25 0.375 0.5
18 3 14 1 3 0.25 0.2857142857142857 0.48148148148148145
18 4 9 1 3 0.42857142857142855 0.4444444444444444 0.5714285714285714
18 4 10 1 3 0.3333333333333333 0.375 0.5454545454545454
18 4 12 1 3 0.3333333333333333 0.4444444444444444 0.5
18 4 13 1 3 0.2 0.375 0.48
18 4 14 1 3 0.2 0.2857142857142857 0.46153846153846156
18 4 11 2 4 0.3333333333333333 0.4 0.5
18 5 9 1 3 0.375 0.4444444444444444 0.55
18 5 9 1 4 0.2857142857142857 0.3 0.5263157894736842
18 5 10 1 3 0.2857142857142857 0.375 0.5238095238095238
18 5 12 1 3 0.2857142857142857 0.4444444444444444 0.4782608695652174
18 5 13 1 3 0.16666666666666666 0.375 0.4583333333333333
18 5 14 1 3 0.16666666666666666 0.2857142857142857 0.44
18 5 10 2 4 0.375 0.45454545454545453 0.5
18 5 11 2 4 0.2857142857142857 0.4 0.47619047619047616
18 5 12 2 4 0.2857142857142857 0.3333333333333333 0.45454545454545453
18 5 9 3 5 0.375 0.4166666666666667 0.5
18 6 9 1 3 0.3333333333333333 0.4 0.5263157894736842
18 6 9 1 4 0.25 0.3 0.5
18 6 10 1 3 0.25 0.3333333333333333 0.5
18 6 12 1 3 0.25 0.4 0.45454545454545453
18 6 13 1 3 0.14285714285714285 0.3333333333333333 0.43478260869565216
18 6 14 1 3 0.14285714285714285 0.25 0.4166666666666667
18 6 10 2 4 0.3333333333333333 0.45454545454545453 0.47368421052631576
18 6 11 2 4 0.25 0.4 0.45
18 6 12 2 4 0.25 0.3333333333333333 0.42857142857142855
18 6 8 3 5 0.4 0.46153846153846156 0.5
18 6 9 3 5 0.3333333333333333 0.4166666666666667 0.47058823529411764
18 6 10 3 5 0.3333333333333333 0.36363636363636365 0.4444444444444444
18 6 7 4 6 0.4 0.42857142857142855 0.5

18 7 9 1 3 0.3 0.36363636363636365 0.5
18 7 9 1 4 0.2222222222222222 0.3 0.47058823529411764
18 7 10 1 3 0.2222222222222222 0.3 0.47368421052631576
18 7 12 1 3 0.2222222222222222 0.36363636363636365 0.42857142857142855
18 7 13 1 3 0.125 0.3 0.4090909090909091
18 7 14 1 3 0.125 0.2222222222222222 0.391304347826087
18 7 10 2 4 0.3 0.4166666666666667 0.4444444444444444
18 7 11 2 4 0.2222222222222222 0.36363636363636365 0.42105263157894735
18 7 12 2 4 0.2222222222222222 0.3 0.4
18 7 8 3 5 0.36363636363636365 0.46153846153846156 0.4666666666666667
18 7 9 3 5 0.3 0.4166666666666667 0.4375
18 7 10 3 5 0.3 0.36363636363636365 0.4117647058823529
18 7 8 4 6 0.36363636363636365 0.38461538461538464 0.42857142857142855
18 8 9 1 3 0.2727272727272727 0.3333333333333333 0.47058823529411764
18 8 9 1 4 0.2 0.2727272727272727 0.4375
18 8 10 1 3 0.2 0.2727272727272727 0.4444444444444444
18 8 12 1 3 0.2 0.3333333333333333 0.4
18 8 13 1 3 0.1111111111111111 0.2727272727272727 0.38095238095238093
18 8 14 1 3 0.1111111111111111 0.2 0.36363636363636365
18 8 10 2 4 0.2727272727272727 0.38461538461538464 0.4117647058823529
18 8 11 2 4 0.2 0.3333333333333333 0.3888888888888889
18 8 12 2 4 0.2 0.2727272727272727 0.3684210526315789
18 8 9 3 5 0.2727272727272727 0.38461538461538464 0.4
18 8 10 3 5 0.2727272727272727 0.3333333333333333 0.375
18 9 10 1 3 0.18181818181818182 0.25 0.4117647058823529
18 9 12 1 3 0.18181818181818182 0.3076923076923077 0.3684210526315789
18 9 13 1 3 0.1 0.25 0.35
18 9 14 1 3 0.1 0.18181818181818182 0.3333333333333333
18 9 10 2 4 0.25 0.35714285714285715 0.375
18 9 11 2 4 0.18181818181818182 0.3076923076923077 0.35294117647058826
18 9 12 2 4 0.18181818181818182 0.25 0.3333333333333333
18 9 10 3 5 0.25 0.3076923076923077 0.3333333333333333
18 10 12 1 3 0.16666666666666666 0.2857142857142857 0.3333333333333333
18 10 13 1 3 0.09090909090909091 0.23076923076923078 0.3157894736842105
18 10 14 1 3 0.09090909090909091 0.16666666666666666 0.3
18 10 11 2 4 0.16666666666666666 0.2857142857142857 0.3125
18 10 12 2 4 0.16666666666666666 0.23076923076923078 0.29411764705882354
18 11 12 1 3 0.15384615384615385 0.26666666666666666 0.29411764705882354
18 11 13 1 3 0.08333333333333333 0.21428571428571427 0.2777777777777778
18 11 14 1 3 0.08333333333333333 0.15384615384615385 0.2631578947368421
18 11 12 2 4 0.15384615384615385 0.21428571428571427 0.25
18 12 13 1 3 0.07692307692307693 0.2 0.23529411764705882
18 12 14 1 3 0.07692307692307693 0.14285714285714285 0.2222222222222222
18 13 14 1 3 0.07142857142857142 0.13333333333333333 0.17647058823529413
19 3 14 1 3 0.25 0.375 0.5
19 3 15 1 3 0.25 0.2857142857142857 0.4827586206896552
19 4 10 1 3 0.42857142857142855 0.4444444444444444 0.5652173913043478
19 4 11 1 3 0.3333333333333333 0.375 0.5416666666666666
19 4 13 1 3 0.3333333333333333 0.4444444444444444 0.5
19 4 14 1 3 0.2 0.375 0.48148148148148145
19 4 15 1 3 0.2 0.2857142857142857 0.4642857142857143
19 4 12 2 4 0.3333333333333333 0.4 0.5
19 5 10 1 3 0.375 0.4444444444444444 0.5454545454545454
19 5 10 1 4 0.2857142857142857 0.3 0.5238095238095238
19 5 11 1 3 0.2857142857142857 0.375 0.5217391304347826
19 5 13 1 3 0.2857142857142857 0.4444444444444444 0.48
19 5 14 1 3 0.16666666666666666 0.375 0.46153846153846156
19 5 15 1 3 0.16666666666666666 0.2857142857142857 0.4444444444444444
19 5 11 2 4 0.375 0.45454545454545453 0.5
19 5 12 2 4 0.2857142857142857 0.4 0.4782608695652174
19 5 13 2 4 0.2857142857142857 0.3333333333333333 0.4583333333333333
19 5 10 3 5 0.375 0.4166666666666667 0.5
19 6 10 1 3 0.3333333333333333 0.4 0.5238095238095238
19 6 10 1 4 0.25 0.3 0.5
19 6 11 1 3 0.25 0.3333333333333333 0.5
19 6 13 1 3 0.25 0.4 0.4583333333333333
19 6 14 1 3 0.14285714285714285 0.3333333333333333 0.44
19 6 15 1 3 0.14285714285714285 0.25 0.4230769230769231
19 6 11 2 4 0.3333333333333333 0.45454545454545453 0.47619047619047616
19 6 12 2 4 0.25 0.4 0.45454545454545453
19 6 13 2 4 0.25 0.3333333333333333 0.43478260869565216
19 6 9 3 5 0.4 0.46153846153846156 0.5
19 6 10 3 5 0.3333333333333333 0.4166666666666667 0.47368421052631576
19 6 11 3 5 0.3333333333333333 0.36363636363636365 0.45
19 6 8 4 6 0.4 0.42857142857142855 0.5
19 7 10 1 3 0.3 0.36363636363636365 0.5
19 7 10 1 4 0.2222222222222222 0.3 0.47368421052631576
19 7 11 1 3 0.2222222222222222 0.3 0.47619047619047616
19 7 13 1 3 0.2222222222222222 0.36363636363636365 0.43478260869565216
19 7 14 1 3 0.125 0.3 0.4166666666666667
19 7 15 1 3 0.125 0.2222222222222222 0.4
19 7 11 2 4 0.3 0.4166666666666667 0.45
19 7 12 2 4 0.2222222222222222 0.36363636363636365 0.42857142857142855
19 7 13 2 4 0.2222222222222222 0.3 0.4090909090909091
19 7 9 3 5 0.36363636363636365 0.46153846153846156 0.47058823529411764
19 7 10 3 5 0.3 0.4166666666666667 0.4444444444444444
19 7 11 3 5 0.3 0.36363636363636365 0.42105263157894735
19 7 8 4 6 0.36363636363636365 0.42857142857142855 0.4666666666666667
19 7 9 4 6 0.36363636363636365 0.38461538461538464 0.4375
19 8 10 1 3 0.2727272727272727 0.3333333333333333 0.47368421052631576
19 8 10 1 4 0.2 0.2727272727272727 0.4444444444444444
19 8 11 1 3 0.2 0.2727272727272727 0.45
19 8 13 1 3 0.2 0.3333333333333333 0.4090909090909091
19 8 14 1 3 0.1111111111111111 0.2727272727272727 0.391304347826087
19 8 15 1 3 0.1111111111111111 0.2 0.375
19 8 11 2 4 0.2727272727272727 0.38461538461538464 0.42105263157894735
19 8 12 2 4 0.2 0.3333333333333333 0.4
19 8 13 2 4 0.2 0.2727272727272727 0.38095238095238093
19 8 9 3 5 0.3333333333333333 0.42857142857142855 0.4375
19 8 10 3 5 0.2727272727272727 0.38461538461538464 0.4117647058823529
19 8 11 3 5 0.2727272727272727 0.3333333333333333 0.3888888888888889
19 8 9 4 6 0.3333333333333333 0.38461538461538464 0.4
19 9 10 1 3 0.25 0.3076923076923077 0.4444444444444444
19 9 10 1 4 0.18181818181818182 0.25 0.4117647058823529
19 9 11 1 3 0.18181818181818182 0.25 0.42105263157894735
19 9 13 1 3 0.18181818181818182 0.3076923076923077 0.38095238095238093
19 9 14 1 3 0.1 0.25 0.36363636363636365
19 9 15 1 3 0.1 0.18181818181818182 0.34782608695652173
19 9 11 2 4 0.25 0.35714285714285715 0.3888888888888889
19 9 12 2 4 0.18181818181818182 0.3076923076923077 0.3684210526315789
19 9 13 2 4 0.18181818181818182 0.25 0.35
19 9 10 3 5 0.25 0.35714285714285715 0.375
19 9 11 3 5 0.25 0.3076923076923077 0.35294117647058826
19 10 11 1 3 0.16666666666666666 0.23076923076923078 0.3888888888888889
19 10 13 1 3 0.16666666666666666 0.2857142857142857 0.35
19 10 14 1 3 0.09090909090909091 0.23076923076923078 0.3333333333333333
19 10 15 1 3 0.09090909090909091 0.16666666666666666 0.3181818181818182
19 10 11 2 4 0.23076923076923078 0.3333333333333333 0.35294117647058826
19 10 12 2 4 0.16666666666666666 0.2857142857142857 0.3333333333333333
19 10 13 2 4 0.16666666666666666 0.23076923076923078 0.3157894736842105
19 10 11 3 5 0.23076923076923078 0.2857142857142857 0.3125
19 11 13 1 3 0.15384615384615385 0.26666666666666666 0.3157894736842105
19 11 14 1 3 0.08333333333333333 0.21428571428571427 0.3
19 11 15 1 3 0.08333333333333333 0.15384615384615385 0.2857142857142857
19 11 12 2 4 0.15384615384615385 0.26666666666666666 0.29411764705882354
19 11 13 2 4 0.15384615384615385 0.21428571428571427 0.2777777777777778
19 12 13 1 3 0.14285714285714285 0.25 0.2777777777777778
19 12 14 1 3 0.07692307692307693 0.2 0.2631578947368421
19 12 15 1 3 0.07692307692307693 0.14285714285714285 0.25
19 12 13 2 4 0.14285714285714285 0.2 0.23529411764705882
19 13 14 1 3 0.07142857142857142 0.1875 0.2222222222222222
19 13 15 1 3 0.07142857142857142 0.13333333333333333 0.21052631578947367
19 14 15 1 3 0.06666666666666667 0.125 0.16666666666666666

In [147]:
len(valid)

613